### ISSUE TITLE
Open source checklist

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/stablecoin-studio#1]
- [x] Readme (include a code of conduct and contributing guide section)
- [x] DCO
- [x] Licence file
- [x] Licence headers

- [ ] SonarQube
- [x] Github actions
- [x] Code Coverage
- [x] Branch protection rules
- [x] Add project to Hedera docs site when live (if required)
- [ ] Standardize package name (com.hedera.<name>) (if applicable)
- [X] Add [security.md](http://security.md/) file if the project is not going to be part of the bug bounty program
- [x] Approval from council (if required) 
- [x] Code audit before open sourcing (If required)

- [X] Open source project
