### ISSUE TITLE
[Custodians Library] migrate to new repository & Add example

### ISSUE THREAD

**Issue by AlbertoMolinaIoBuilders** [hashgraph/stablecoin-studio#1036]
- Migrate the Custodial Wallet Library to : https://github.com/hashgraph/hedera-custodians-library
```[tasklist]
### Tasks
- [x] Migrate to new repository
- [x] Add an example to an example folder exaplaining how the library should be used
- [x] Publish new version to NPM
```

**Comment by AlbertoMolinaIoBuilders** [comment]
Migration : 1 day
Deployment (Github action) : 4 days
