### ISSUE TITLE
[CLI] Select version of HederaERC20 when create stable coin

### ISSUE THREAD

**Issue by Axel-IoBuilders** [hashgraph/stablecoin-studio#537]
## Context
When we create an stable coin we use the HederaERC20 which is in our config file.

## Description
When the user is creating an stable coin, we should add the following message:
"What address of HederaERC20 do you want to use?" and a list of addresses that are stored in the StableCoinFactory

## Acceptance criteria
 - As a user, I want to choose the HederaERC20 contract versión to use when creating a stable coin
 - As a user, I want to use last HederaERC20 contract version as default version
 - As a user, I want to know the differences between HederaERC20 contract different versions

```[tasklist]
### Tasks
- [x] [Smartcontracts] Add new method and storage versions addressses
- [x] [SDK] Retrieve the addressess list and update the stablecoin creation flow
- [x] [CLI] Add new question and update creationRequest
- [x] [Documentation] Create a document when show the differents addresses HederaERC20
```

Subtask
| ID | Status      | Description | Owner  |
|----|-------------|-------------|--------|
| 1  | DONE        | [Smartcontracts] Add new method and storage versions addressses  | Axel
| 2  | DONE        | [SDK] Retrieve the addressess list and update the stablecoin creation flow  | Axel
| 3  | TODO        | [CLI] Add new question and update creationRequest  | Owner
| 4  | TODO        | [Documentation] Create a document when show the differents addresses HederaERC20  | Owner
