### ISSUE TITLE
[CLI] Send tokens without fees

### ISSUE THREAD

**Issue by darius279** [hashgraph/stablecoin-studio#543]
## Context
Using the stable coin accelerator give the possibility to create and manages a token. Currently since we are able to add any token to the solution even if you have no rights to manage it, it is good to allow them to transfer tokens to different accounts.

## Description
When the user select a stable coin to operate with, when the token has not been paused or deleted and the current account has not been frozen  we always add a new option in the first position:
"Send tokens"

When the user selects this option, first of all, we will check how many tokens the current account has and add the number next to the Network --- Account -- Stablecoin information: N tokens
If it has no tokens --> Display a message: "You have no tokens" and give it the possibility to "Go back"
If it has tokens --> 
- What is the target account?
- Amount
Each time we add a new account, we should check if the added account is freezed or has not validated the KYC. If this happens we should display an error message.

### Behaviour without fees

When the user has added the target address and the amount we ask it if they want to transfer more tokens. We should avoid this question if the sum of the amounts is exactly the total amount of tokens that the user has. We will display the summary screen.

- "Do you want to send more tokens"?
- If so, repeat both questions.

The user could transfer to as many different accounts as they want.

Each time the user adds an amount, we should check if the sum of all amounts is above the total amount of tokens that the user has.

When the sum that the user has entered is above the amount of tokens that its owns, display the following message:
- Insufficient balance --> and display again the "Amount" option.

#### Summary view
When the user select that it doesn't want to send more tokens we should display the summary with the information regarding the transfers like this example:

Summary
100 HDC --> 0.0.7412
25 HDC --> 0.0.7315

"Do you want to proceed?" Yes - No
If no --> Go back to stable coin menu

"Do you want to proceed?" Yes - No

## Acceptance criteria
- Given a stable coin without fees, If I have 100 tokens, I can send 20 tokens to one account and 80 tokens to another account.
- Given a stable coin without fees, If I have 100 tokens, If I select to send 100 tokens to the first account, automatically will see the summary view.
- Given a stable coin without fees, If I have 100 tokens, If I select to send 150 tokens to the first account, an error message will be displayed.

```[tasklist]
### SubTask
- [ ] TODO - [CLI] Create questions
- [ ] TODO - [SDK] Create multitransfer operation
- [ ] TODO - [SDK] Test and update doc
```
