### ISSUE TITLE
[CLI] Rescue HBARs from contract

### ISSUE THREAD

**Issue by AlbertoMolinaIoBuilders** [hashgraph/stablecoin-studio#603]
## Context

SC proxy smart contract will be set as the auto renew account of the underlying token, which means that it will need to have HBARs in order to pay for the token extensions. 
It could happen that some HBARs get "trapped" in the contract if for some reason the token is deleted and the contract still owns HBARs.

## Description

It would be necessary to implement a rescue HBAR method, just like the current rescue method, that would allow users with the "rescue" role to withdraw HBARs from the contract.

We should add a new option only available for the users with the rescue role that allow the user to rescue HBARs from the SmartContract to the rescue account.

When the user select this option, we should ask: "How many HBARs do you want to rescue?"

##  Acceptance criteria
- When I've the rescuer role, I have a new option called Rescue HBARs 
- When I select the rescue HBARs options and given a SmartContract with 100 HBARs, I can rescue 10 HBARs.
- Given a user without the rescue role, I cannot see the "Rescue HBARs" option

## Tasks
```[tasklist]
### Tasks
- [x] SC - Implement SC code
- [x] SDK - Implement new feature
- [x] CLI - Add questions and call SDK
- [x] SmartContract testing
- [x] SDK testing
- [x] DOC - Update documentation
```
