### ISSUE TITLE
Add test into de pipeline

### ISSUE THREAD

**Issue by darius279** [hashgraph/stablecoin-studio#615]
## Context

In order to guarantee that our solution is reliable we should ensure that when we merge some code to main branch, everything continue working. For that reason, we should add our current test set to the pipeline.

## Description

When the user merge some branch to main branch, we should launch the test set and if fails, roll back the merge.

##  Acceptance criteria
- When I merge a branch into main branch, test are successfully executed and the code merged
- When I merge a branch into main branch, test are not successfully executed and the code are not merged

## Tasks

```[tasklist]
### Tasks
- [x] Create docker image
- [ ] Upload docker image at gitHub actions
- [ ] Find out where we should upload the docker image
- [ ] Configure test within gitHub actions
```
