### ISSUE TITLE
[CLI] Upgrade proxy version

### ISSUE THREAD

**Issue by darius279** [hashgraph/stablecoin-studio#627]
## Context
Our stable coin needs a proxy that creates and manage all the operations related with them, this proxy could be upgraded with new features. When the user deploys a stable coin an they are working for a long time, it is possible that some new updated has been made to the proxy, for that reason, the users should be able to update its current proxy implementation.

## Description
When the user selects a stable coin to operate with, within "Configuration" option, if the account is the proxy admin owner, a new option will be displayed in the last position called:
"Upgrade proxy version"

When the users selects this version will be displayed the following options:
- Upgrade to last proxy version
- Select version to upgrade

### Upgrade to last proxy version
Your proxy will be upgrade to the "x.x" version, do you want to proceed?
If so, upgrade to this version. If no, go back.

### Select version to upgrade
A list with all proxy version available will be displayed. At least will be only one displayed. 
The last option will be "Introduce your proxy id"

When the user selects one of them we will display the following question.
Your proxy will be upgrade to the "x.x" version, do you want to proceed?
If so, upgrade to this version. If no, go back.

##  Acceptance criteria
- When the users is working with the last version of a proxy, Configuration option is disabled
- When the user is working with a version that is not de last one. "Upgrade proxy version" option is displayed.
- When the user is working with a version that is not de last one and selects "Upgrade proxy version" option the user can update to last proxy version.
- When the user is working with a version that is not de last one and selects "Upgrade proxy version" option the user can selects one of the newest proxy versions.

## Tasks

```[tasklist]
### Tasks
- [ ] [CLI] Add new option and display information in the stable coin details
- [ ] [SDK] Add new feature
- [ ] [Test] SDK testing
- [ ] [Doc] Update doc
```
