### ISSUE TITLE
[CLI] Add custom mirror node

### ISSUE THREAD

**Issue by darius279** [hashgraph/stablecoin-studio#640]
## Context
Hedera mirror nodes are designed to provide real-time access to the Hedera network's transaction and consensus state data. However, like any distributed system, there can be reliability issues that arise from time to time. Some of the reliability problems that Hedera mirror nodes can experience include networks connectivity or data latency.

Hedera mirror nodes are public and available for everybody. If there are issue with the node, such as congestions or outages due to a massive utilization of the mirror, the solutions could have delays receiving data from them.

To address these reliability issues and to ensure that real time applications could be operative without any interruption, be scalable and provide as many infrastructure resources as necessary depending the applications necessity, we should allow the stable coin users the possibility to choose between public and private mirror nodes and RPCs. 

## Description
When the user open the CLI, within “Configuration” option, we will include a new option call “Mirror node configuration” after the “Manage accounts” option.

Within “Mirror node configuration” option, there will be three more for the different environments:

- Testnet
- Previewnet
- Mainnet

When the user selects one environment to configure, it will see:

As a title: 

Node configuration: Hedera mirror node (by default)

As an options: 

- Change current node configuration
- Display configured nodes
- Set up mirror node
- Remove mirror node
- Go Back

 

Change current node configuration:  When the user selects this option, it should be able to choose between “Hedera mirror node” and as many nodes has been configured. Once the user has changed the current node configuration, the selected node will be used until it is changed again, although the session was closed. The last option will be always “Go Back”. Example:

Choose you current “testnet” node configuration:

- Hedera local node
- Arkhia: ***1234
- Go back

Display configured nodes: When the user selects this option, it should be able to see what configurations are set if the user has created some of them. Example:

Configured nodes:

- Local node: http://localhost:3000
- Arkhia: http://pool.arkhia.io/hedera/mainnet/api/v1 key: ***1234

Set up mirror node: When the user selects this new option some questions will be prompted:

Introduce the node name:

Introduce the url:

Introduce the port:

Do you need an api key? (Yes/No)

If so:

Introduce your http header: 

Introduce your api key:

Remove mirror node: When the user selects this option, a list with all the custom nodes will be displayed. Hedera mirror node and the current node won’t be displayed. The user will be able to select one of them. When the user select the one that would be delete it, a confirming question will be prompted:

Are you sure do you want to delete “node name”?

If so, delete the node from configuration.

Go back: Go to previous menu

Non-functional requirements

When a user selects one of the custom nodes, we should configure the queries in order to point to the preconfigured node.

##  Acceptance criteria
- 

## Tasks

```[tasklist]
### Tasks
- [x] [CLI] File config management, add service, remove service, select, list
- [x] [SDK] Use service from configuration file
- [x] [Test] Implement testing
- [ ] [Doc] Update doc
```
