### ISSUE TITLE
[CLI] Add custom RPC relay

### ISSUE THREAD

**Issue by darius279** [hashgraph/stablecoin-studio#641]
## Context
Hedera mirror nodes are designed to provide real-time access to the Hedera network's transaction and consensus state data. However, like any distributed system, there can be reliability issues that arise from time to time. Some of the reliability problems that Hedera mirror nodes can experience include networks connectivity or data latency.

Hedera mirror nodes are public and available for everybody. If there are issue with the node, such as congestions or outages due to a massive utilization of the mirror, the solutions could have delays receiving data from them.

To address these reliability issues and to ensure that real time applications could be operative without any interruption, be scalable and provide as many infrastructure resources as necessary depending the applications necessity, we should allow the stable coin users the possibility to choose between public and private mirror nodes and RPCs. 

## Description
The users will be able to configure where RPC queries should point, for that reason, we should give them the possibility to add as many RPC urls as necessary. Within “Configuration” section and after choosing the environment, we will add a new option called “Set up RPC”:

As an options: 

- Change current node configuration
- Display configured nodes
- Set up mirror node
- Set up RPC
- Remove mirror node
- Go Back

When the user selects this new options, some questions will be prompted:

Introduce the RPC name:

Introduce the url:

Introduce the port:

Do you need an api key? (Yes/No)

If so: 

Introduce your http header:

Introduce your api key:

Non-functional requirements

When a user selects one of the custom RPC, we should configure the queries in order to point to the preconfigured RPC.
##  Acceptance criteria
- 

## Tasks
```[tasklist]
### Tasks
- [x] [CLI] File config management, add service, remove service, select, list
- [x] [SDK] Use service from configuration file
- [x] [Test] Implement testing
- [ ] [Doc] Update doc
```
