### ISSUE TITLE
[CLI] New 'Manage factory' main menu option

### ISSUE THREAD

**Issue by darius279** [hashgraph/stablecoin-studio#677]
## Description
Within the "Configuration" main menu option we should add a new option called: 
"Manage factory".
This option will contain four suboptions:

- Change factory
- Upgrade factory
- Change owner
- Factory details

### Change factory
This option allows the user to change the factory id of the factory configured in the CLI configuration file.
Once the user has selected this option, it will have to select the Hedera network whose factory id is going to be changed. After that, it should enter the new factory id. Then, the factory id of the selected Hedera environment will be change in the CLI config file.
Any account will be able to view this option in the menu and, therefore, to perform the action.

### Upgrade factory
This option allows the user to upgrade the current factory configured in the CLI configuration file for the Hedera network to which the working account belongs.
Once the user has selected this option, it will only have to enter the new factory contract implementation, so the current factory proxy will point to this new implementation rather than the old one. 
Only the factory owner account will be able to view this option in the menu and perform the action through the factory proxy admin contract.

### Change owner factory
This option allows the user to change the owner account of the factory.
Once the user has selected this option, it will only have to enter the new factory owner account. 
Only the factory owner account will be able to view this option in the menu and perform the action through the factory proxy admin contract.

### Factory details
This option allows the user to view the factory current implementation address and the owner account.
Any account will be able to view this option in the menu and, therefore, to perform the action.

##  Acceptance criteria

- Any account can view the new 'Manage factory' main menu option.
- An account that is not the factory owner can only view the 'change factory' and 'factory details' suboptions.
- An account that is the factory owner can view the four suboptions.
- Any user can change the factory id of the selected Hedera network. It does not mind if a factory already exists in the configuration file for the selected Hedera network.
- When the user changes the factory, we can create a token with the new factory.
- Only factory onwer account can upgrade the factory.
- When the user upgrades the factory, we can create a token with the new factory implementation.
- Only factory onwer account can change the factory owner.
- When the user changes the factory owner, the user will not be able to upgrade the factory and change the owner. On the contrary, the new owner account, will be able.
- Any account will be able to view the current factory implementation and the factory owner.
 
## Tasks

```[tasklist]
### Tasks
- [x] [CLI] Add new menu option with the four suboptions
- [ ] [CLI] Tests
- [x] [SDK] Manage the four suboptions
- [ ] [SDK] Tests
- [x] [DOC] Update documentation
```
