### ISSUE TITLE
[CLI] Refactor code

### ISSUE THREAD

**Issue by martineziob** [hashgraph/stablecoin-studio#684]
All info about this refactor is in this confluence -> https://iobuilders.atlassian.net/wiki/spaces/IA/pages/2814279693/SPIKE+-+Refactor+CLI

```[tasklist]
### Tasks
- [x] Refactor SetConfigurationService
- [x] Refactor WizardService
- [x] Refactor repeated code
- [x] Test mirror, rpc and factories manage in cli
- [x] Integrate in actual sprint (merge and resolve conflicts)
```
