### ISSUE TITLE
[Smart Contract] Add scripts for SC upgradability checks

### ISSUE THREAD

**Issue by AlbertoMolinaIoBuilders** [hashgraph/stablecoin-studio#686]
We should create scripts that check if a newer version of the "HederaTokenManager" and/or "StableCoinFactory" contracts is compatible with the previous one (in terms of storage allocation).
Some scripts were already created in this brach : 
https://github.com/hashgraph/hedera-accelerator-stablecoin/tree/feature/upgradable

The idea is to integrate them into the deployment process so that we make sure that we do not deploy anything that is not compatible.
```[tasklist]
### Tasks
- [ ] Define best practices
- [ ] Check current scripts
- [ ] Update internal doc
```
