### ISSUE TITLE
[CLI] Add timelock when upgrading the proxy

### ISSUE THREAD

**Issue by darius279** [hashgraph/stablecoin-studio#712]
## Description
During the stable coin creation, we should add one last question within the "optional" stable coin details option. (decimals, initial supply, etc).
Introduce the minutes of delay to execute administration changes.
By default: 0

When the stable coin owner wants to modify the proxy or the timelock delay itself, these operation should have the timelock delay.

We should add a new option for the admin that allow them to modify the current delay.

We should add a new menu option only visible by the stable coin Owner and Admin that displays the current operations to confirm like the proxy update or the timelock update time. Within this menu, when the user select one of them, a prompt will be displayed:
"Do you want to confirm this operation? Yes / No.
If so, confirm the operation.

##  Acceptance criteria

- I can configure the timelock during the stable coin creation
- I can modify the current timelock
- I can schedule a proxy change with the timelock
- I can confirm a pending operation

```[tasklist]
### Tasks
- [ ] [SC] Add timelockcontroller
- [ ] [SDK] Create the confirmation operation, edit delay
- [ ] [CLI] Add timelock configuration, confirmation operation and edit delay operation
- [ ] [Testing] Check the current implementation, SC, SDK and CLI
- [ ] [Doc] Create documentation
```
